### ISSUE TITLE
로그인 기능

### ISSUE THREAD

**Issue by codenee** [f-lab-edu/next-commerce#5]
- 개발 목표
   이메일, 패스워드 값을 입력 받아 회원 가입이 완료된 사용자인지 검사 후 로그인 기능을 제공한다. 
회원 가입이 되지 않은 사용자라면 회원 가입 기능을 제공한다.
로그인 세션 관리를 학습하기 위해 세션, 토큰 방식을 구현해보자.

- 입력
   이메일, 패스워드

- [x] 이메일
- [x] 패스워드
- [x] 검사

로그인 세션 관리로 토큰 방식과 세션 방식이 있다.
  세션은 spring session + redis
  토큰은 spring security +redis + jwt
조합으로 많이 사용하는 것 같다.

**Comment by f-lab-ben** [comment]
쿠키 vs 세션

토큰방식 -> 쿠키
